import Head from 'next/head'
import Navbar from './navBar.js'
import Footer from './footer.js'
import styles from '../styles/Home.module.css'

const data = {
  "firstname": "Maximilian",
  "lastname": "Forstenhäusler",
}
const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ""

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>My personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Navbar}>
        <Navbar firstname={data.firstname} lastname={data.lastname} prefix={prefix}/>
      </div>
      <main className={styles.main}>
          {children}
      </main>
      <div className={styles.Footer}>
        <Footer prefix={prefix}/>
      </div>
    </div>
  )
}